### ISSUE TITLE
why both tsconfig-esm.json	 and tsconfig.json?

### ISSUE THREAD

**Issue by xmlking** [mgechev/ngresizable#1]
Frist of all, thanks for a gready blog post [Distributing an Angular Library - The Brief Guide blog](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/)
 just wonder why you have two config files i.e.,  `tsconfig-esm.json`	 and `tsconfig.json` in this repo. 
Is there any specific need for it?
 your `package.json` only refers to `tsconfig-esm.json`

**Comment by mgechev** [comment]
It's used by `ngc`, which was incorrectly referencing to `tsconfig-esm.json`.
