### ISSUE TITLE
Is dom needed in the tsconfig lib compiler option?

### ISSUE THREAD

**Issue by oleersoy** [mgechev/ngresizable#10]
Hi - I read your very awesome [article](http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/).  Just curious whether the `dom` option is still needed in the tsconfig.json, since it's not a good idea to access the dom directly?

**Comment by mgechev** [comment]
It's used only for providing type definitions for DOM-related APIs, in case required.

Unfortunately, at this moment there's almost no way to develop a complete application without accessing the DOM since `Renderer2` doesn't provide complete enough API.

**Comment by oleersoy** [comment]
OK - Thanks - Appreciate your feedback.
