### ISSUE TITLE
Unable to drag to select text in any controls in Chrome

### ISSUE THREAD

**Issue by aprapplicationsupport** [mgechev/ngresizable#12]
When I add the ngResizable attribute to any div on the page, none of the html controls are able to be click and drag highlighted.

On the [demo](https://mgechev.github.io/ngresizable/) page for instance, if you add a `<p>foo</p>`, `<input type="textbox">`, etc to the page source in the Chrome source inspector, none of the text is able to be click-and-drag highlighted.

I'm on Chrome version 59.0.3071.104

**Comment by mgechev** [comment]
Yes, if you add the directive to new element in the inspector resize is not supposed to work.

Angular doesn't observe the DOM for changes.
