### ISSUE TITLE
How can we use ngResizable on a flex item?

### ISSUE THREAD

**Issue by racerhere** [mgechev/ngresizable#13]
Please take a look at this Plunkr: [https://plnkr.co/edit/uCtuMK6Jk3AJAx6qPI4V](https://plnkr.co/edit/uCtuMK6Jk3AJAx6qPI4V).

I am trying to have a persistent side content (25% on left side) and trying to get a resizable div on the top of the remaining 75% on  right.

The grabber div `div.ngr-grabber.ngr-bottom` is always at the bottom of the page.

Any help is appreciated.

**Comment by mgechev** [comment]
Thanks for the plnkr. I will take a look later today.

**Comment by racerhere** [comment]
Hi @mgechev, Did you get a chance to look into my issue, please?

**Comment by mgechev** [comment]
@racerhere I cannot open the demo that you've provided, I get an error.

`ngresizable` works with `position` `absolute` and `relative`. It doesn't support `flex` at the moment.

I'll add information about this in the readme.
