### ISSUE TITLE
After applying ngResizer not able to select any DOM element text.

### ISSUE THREAD

**Issue by MatellioAabid** [mgechev/ngresizable#15]
After applying ngResizer not able to select any dom element text. As of my knowledge, i have checked the code and found that in library OnMouseMove event using preventDefault that's why facing this issue.
And also OnMouseMove event is bound to document not only on the particular element. Please let me know how to fix this issue.

**Comment by mgechev** [comment]
Prevent default might be causing the issue. Will take a look at it today. The other observation you made is correct and implemented property.

**Comment by maabiddevra** [comment]
Resolved this issue in pull request #16. Please merge this pull request.

**Comment by mgechev** [comment]
Closed by https://github.com/mgechev/ngresizable/pull/16.
Will release tomorrow.
