### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by manju-reddys** [mgechev/ngresizable#4]
Hello,

With Agular cli I get following error:

"moduleId should be a string in "NgResizableComponent". See https://goo.gl/wIDDiL for more information.
If you're using Webpack you should inline the template and the styles, see https://goo.gl/X2J8zc."

**Comment by mgechev** [comment]
Thanks for pointing this out. Fixed in version 0.1.2.

Seems like an issue in CLI, I'll investigate it further and may open a PR there as well.

**Comment by mgechev** [comment]
Here's further information https://github.com/angular/angular-cli/issues/3576.
