### ISSUE TITLE
Building NgResizable

### ISSUE THREAD

**Issue by Karasuni** [mgechev/ngresizable#5]
Are there any requirements for building and testing the NgResizable package?

I've tried the following:

```
git clone git@github.com:mgechev/ngresizable.git
cd ngresizable
npm i
npm run build
npm run test
```

`npm run build`  claims that it cannot find the `fs` module even though my IDE resolves the module to `node_modules/@types/node/index.d.ts`.

```
C:\dev\projects\examples\ngresizable\node_modules\ts-node\src\index.ts:319
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
tools\inline-styles.ts (1,45): Cannot find module 'fs'. (2307)
```

A similar issue appears using `npm test`:

```
> ngresizable@0.1.2 test C:\dev\projects\examples\ngresizable
> mocha --require ts-node/register test/**/*.spec.ts --recursive

C:\dev\projects\examples\ngresizable\node_modules\ts-node\src\index.ts:319
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
    at getOutput (C:\dev\projects\examples\ngresizable\node_modules\ts-node\src\index.ts:319:17)
```

NgResizable version: bf674554ab236083e2fb5403657092c6a5a1a929
Platform: `Windows 10`
Typescript version: `2.1.6`
NPM version: `4.2.0`

**Comment by mgechev** [comment]
I can't reproduce it but have an idea from where this inconsistent behavior could be.

Would you try again? For `npm t` you don't need to run `npm run build`.

**Comment by Karasuni** [comment]
This solutions works for me. The only adjustments I've had to do is change the following:
`cp package.json dist` >> `copy package.json dist`
`cp README.md dist` >> `copy README.md dist`
`mv lib/ngresizable.component.ts.bak lib/ngresizable.component.ts` >> `move /Y lib\\ngresizable.component.ts.bak lib\\ngresizable.component.ts`

considering the Windows environment I'm in. I'm looking into setting up a Vagrant server for a more consistent behavior across distributions. Maybe it would be interesting to migrate the npm scripts and build-demo into gulp tasks to avoid having platform-specific operations.
